services:
  db:
    image: postgres
    volumes:
      - ./container_db:/var/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace
    working_dir: /workspace
    command: sleep infinity
    ports: 
      - '3000:3000'
    depends_on:
      -  db